[project]
name = "borrajas"
version = "0.1.0"
description = "Hybrid RDF+RAG question-answering system for extreme weather events"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "chromadb>=1.5.9",
    "langchain-chroma>=1.1.0",
    "langchain-text-splitters>=1.1.2",
    "python-dotenv>=1.2.2",
    "rdflib>=7.6.0",
]

[project.optional-dependencies]
langgraph = [
    "langgraph>=1.2.1",
    "langchain-core",
    "langchain-ollama>=1.1.0",
]
ui = [
    "chainlit>=2.11.1",
]
oxigraph = [
    "oxrdflib>=0.5.0"
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[project.scripts]
borrajas-cli = "borrajas.cli:main"
#borrajas-ui = "borrajas.ui.app:main"
#borrajas-eval = "borrajas.eval:main"

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"
